theme: jekyll-theme-minimal
title: Pavan Kumar Ramadugu
show_downloads: True
cv: https://drive.google.com/file/d/1stsV2nlaCm0sye4MQy89FkHktzXS4Bj5/view
navigation:
  - title: Home
    url: /
  - title: Contact
    url: contact
